version: '3.8'
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: dbpassword
            MYSQL_DATABASE: beerservice
        ports:
          - '3306'    
    jms:
        image: apache/activemq-artemis:2.39.0
        ports:
            - 8161:8161
            - 61616:61616
