services:
  jms:
    container_name: jms
    image: apache/activemq-artemis:2.40.0
    ports:
      - 8161:8161
      - 61616:61616
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: simetraehcapa
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161" ]
      interval: 10s
      timeout: 5s
      retries: 5  
