apiVersion: v2
name: kbe-brewery-order-micro-service-jms
description: A Helm subchart for jms
type: application
# Disable Sonar warning for invalid semver: This value is set by Maven filtering
# and will be replaced with a valid version number during the build process.
version: @helm.chart.version@
appVersion: @project.version@
