apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-template.fullname" . }}-spring-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_HIKARI_USERNAME: {{ .Values.mysql.user | quote }}
  SPRING_DATASOURCE_HIKARI_PASSWORD: {{ .Values.mysql.password | quote }}
  SPRING_ARTEMIS_USER: {{ .Values.jms.user | quote }}
  SPRING_ARTEMIS_PASSWORD: {{ .Values.jms.password | quote }}