apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.service.rootPassword | quote }}

  MYSQL_USER: {{ .Values.service.user | quote }}
  MYSQL_PASSWORD: {{ .Values.service.password | quote }}
